version: "3"

services:
  app:
    build: .
    labels:
      - "traefik.http.routers.cc-haiku.rule=Host(`cc-haiku.lipsumar.io`)"
      - "traefik.http.routers.cc-haiku.tls.certresolver=le"
      - "traefik.http.routers.cc-haiku.entrypoints=websecure"
      - "traefik.docker.network=traefik-external"
    networks:
      - traefik-external
      - internal
    depends_on:
      - mongo
    volumes:
      - /mnt/volume_lipsumar_io_main/cc-haiku/haiku-images:/usr/src/app/public/haiku-images
  mongo:
    image: mongo
    networks:
      - internal
    labels:
      - "traefik.enable=false"
    volumes:
      - /mnt/volume_lipsumar_io_main/cc-haiku/db:/data/db
    #ports:
    #  - 27017:27017
  image_service:
    build: ./src/image-generation/
    ports:
      - 5000:5000
    networks:
      - internal
    labels:
      - "traefik.enable=false"
networks:
  traefik-external:
    external: true
  internal:
    external: false
