version: '3'

services:
  app:
    build: .
    labels:
      - "traefik.http.routers.cc-haiku.rule=Host(`cc-haiku.lipsumar.io`)"
      - "traefik.http.routers.cc-haiku.tls.certresolver=le"
      - "traefik.http.routers.cc-haiku.entrypoints=websecure"
      - "traefik.docker.network=traefik-external"
    networks:
      - traefik-external
      - internal
    depends_on: 
      - mongo
  mongo:
    image: mongo
    networks: 
      - internal
    labels: 
      - "traefik.enable=false"

networks:
  traefik-external:
    external: true
  internal:
    external: false